"""Curated SE1 cards. Card = (question, correct, [three wrong], why). Slide-literal; mirrors the notes."""

KEEP_M3_IDX = [6, 10, 15, 21, 22, 23, 24, 26, 28, 30, 32, 33, 35, 36]
KEEP_M4_IDX = [4, 5, 8, 9, 13, 14, 15, 18, 19, 20, 21, 22, 23, 24, 27, 28, 29, 33, 35, 37, 38]

M3_NEW = [
    ("Which Agile value is placed ABOVE processes and tools?", "Individuals and interactions", ["Working software", "Customer collaboration", "Responding to change"], "Four values"),
    ("According to the Agile values, working software is valued over what?", "Comprehensive documentation", ["Contract negotiation", "Following a plan", "Processes and tools"], "Four values"),
    ("According to the Agile values, customer collaboration is valued over what?", "Contract negotiation", ["Comprehensive documentation", "Following a plan", "Processes and tools"], "Four values"),
    ("According to the Agile values, responding to change is valued over what?", "Following a plan", ["Contract negotiation", "Comprehensive documentation", "Processes and tools"], "Four values"),
    ("In Agile, what is the primary measure of progress?", "Working software", ["Pages of documentation", "Hours worked", "Number of meetings"], "Principles"),
    ("Which Agile principle describes the best form of communication?", "Face-to-face conversation (co-location)", ["Email pass-around", "Detailed written contracts", "Weekly status reports"], "Principles"),
    ("Which statement about Waterfall is correct?", "The customer can only see the product at the end of the project", ["The customer sees the product after every iteration", "Testing happens in every iteration", "Developers and testers work together every sprint"], "Agile vs Waterfall"),
    ("Which statement about Agile is correct?", "Every iteration has its own testing phase", ["Testing happens only after the whole development phase", "Documentation is the top priority", "User acceptance happens only at the end of the project"], "Agile vs Waterfall"),
    ("In which model is documentation a TOP priority and can be used to train staff?", "Waterfall", ["Agile", "Scrum", "XP"], "Agile vs Waterfall"),
    ("Agile iterations in the Agile vs Waterfall comparison run for how long?", "2 to 4 weeks", ["1 to 2 days", "6 to 8 weeks", "6 months"], "Agile vs Waterfall"),
    ("What is Scrum?", "An agile process framework for managing complex knowledge work", ["A programming language", "A type of Waterfall phase", "A testing tool"], "Scrum definition"),
    ("Scrum is designed for teams of how many members?", "Ten or fewer", ["Exactly three", "At least twenty", "Fifty or more"], "Scrum definition"),
    ("What is the maximum length of a sprint?", "One month", ["One week", "Two days", "One quarter"], "Sprint"),
    ("What is the most common sprint length?", "Two weeks", ["One day", "Six weeks", "Three months"], "Sprint"),
    ("Which Scrum role is the facilitator who removes impediments and enforces scrum rules?", "Scrum Master", ["Product Owner", "Development Team", "Stakeholder"], "Roles"),
    ("Which Scrum role represents the stakeholders and administers the backlog?", "Product Owner", ["Scrum Master", "Development Team", "Project Sponsor"], "Roles"),
    ("Which Scrum role prioritizes goals for each sprint based on value to stakeholders?", "Product Owner", ["Scrum Master", "Development Team", "Tester"], "Roles"),
    ("A scrum development team is made up of how many people?", "Three to ten", ["One to two", "Eleven to twenty", "Exactly seven"], "Roles"),
    ("Which sprint event is recommended to last four hours for a two-week sprint?", "Sprint Planning", ["Daily Scrum", "Sprint Review", "Sprint Retrospective"], "Time boxes"),
    ("How long is the daily scrum timebox?", "15 minutes", ["30 minutes", "1 hour", "4 hours"], "Time boxes"),
    ("What is the recommended duration of a sprint review for a two-week sprint?", "Two hours", ["Four hours", "Fifteen minutes", "One day"], "Time boxes"),
    ("What is the recommended duration of a sprint retrospective for a two-week sprint?", "One and a half hours", ["Two hours", "Four hours", "Fifteen minutes"], "Time boxes"),
    ("Which Scrum event is facilitated by the Scrum Master and asks what went well and what did not?", "Sprint Retrospective", ["Sprint Review", "Sprint Planning", "Backlog Refinement"], "Retrospective"),
    ("Which is NOT one of the three daily scrum questions?", "Who is to blame for the delay?", ["What did I complete yesterday?", "What do I plan to complete today?", "Do I see any impediment?"], "Daily scrum"),
    ("What is backlog refinement formerly called?", "Grooming", ["Chartering", "Wrapping", "Retrospective"], "Backlog refinement"),
    ("In sprint planning, the short description of what the team forecasts to deliver is called the...", "Sprint goal", ["Product backlog", "Sprint review", "Impediment"], "Sprint planning"),
    ("Who is responsible for the Crystal methodology?", "Alistair Cockburn", ["Roy Fielding", "Winston Royce", "Kent Beck"], "Crystal"),
    ("Crystal focuses primarily on what?", "People and their interactions", ["Processes and tools", "Documentation", "Contracts"], "Crystal"),
    ("What are the three phases of Crystal?", "Chartering, Cyclic Delivery, Wrap Up", ["Planning, Analysis, Design", "Pre-project, Feasibility, Business Study", "Plan, Do, Check"], "Crystal phases"),
    ("In Crystal, creating the team and building an initial plan happens in which phase?", "Chartering", ["Cyclic Delivery", "Wrap Up", "Closure"], "Crystal phases"),
    ("In DSDM, what stays variable when time and budget are fixed?", "The requirements", ["The deadline", "The budget", "The team size"], "Timeboxing"),
    ("In DSDM timeboxing, which requirements are omitted when time or money runs out?", "The lowest priority ones", ["The highest priority ones", "The oldest ones", "The ones the team likes least"], "Timeboxing"),
    ("What does MoSCoW stand for?", "Must have, Should have, Could have, Won't have", ["Must do, Should do, Could do, Will do", "Manage, Observe, Specify, Control, Work", "Model, Scope, Code, Wrap"], "MoSCoW"),
    ("MoSCoW is used in DSDM for what?", "Prioritizing requirements", ["Estimating cost", "Writing code", "Drawing diagrams"], "MoSCoW"),
    ("Which DSDM technique builds early versions so users can test-drive the system?", "Prototyping", ["Timeboxing", "MoSCoW", "Refactoring"], "Prototyping"),
    ("How many phases does DSDM have in the module?", "Seven", ["Three", "Five", "Eight"], "DSDM phases"),
    ("Which DSDM phase comes right before Implementation?", "Design and Build Iteration", ["Business Study", "Feasibility Study", "Post-project"], "DSDM phases"),
    ("Which is the last DSDM phase?", "Post-project", ["Implementation", "Pre-project", "Closure"], "DSDM phases"),
    ("FDD is focused around designing and building what?", "Features", ["Sprints", "Stories", "Classes only"], "FDD"),
    ("How many practices does FDD list in the module?", "Eight", ["Three", "Five", "Twelve"], "FDD practices"),
    ("Which is one of the FDD practices?", "Feature Teams", ["Daily Scrum", "Planning Poker", "Pair Programming"], "FDD practices"),
    ("Lean software development is adapted from which system?", "Toyota Production System", ["Waterfall", "Capability Maturity Model", "Rational Unified Process"], "Lean"),
    ("Lean is based on which production principle?", "Just in time production", ["Mass production", "Batch production", "Make to stock"], "Lean"),
    ("How many Lean principles are listed in the module (Chapter 2)?", "Seven", ["Four", "Ten", "Twelve"], "Lean principles"),
    ("Which Lean principle says software value is measured in fitness for use?", "Amplifying learning", ["Eliminating waste", "Early delivery", "Building integrity"], "Lean principles"),
    ("Which Lean principle says to delay decisions until they can be based on facts?", "Defer commitment", ["Early delivery", "Empowering the team", "Optimize the whole"], "Lean principles"),
    ("Which Lean principle matches the idea 'not the biggest that survives, but the fastest'?", "Early delivery", ["Eliminating waste", "Defer commitment", "Building integrity"], "Lean principles"),
    ("Which Lean principle covers the customer's overall experience of the system, such as how it is advertised, delivered, and priced?", "Building integrity", ["Optimize the whole", "Amplifying learning", "Eliminating waste"], "Lean principles"),
    ("Which phrase goes with 'Optimize the whole'?", "Think big, act small, fail fast; learn rapidly", ["Just in time", "Build it and they will come", "Move fast and break things"], "Lean principles"),
    ("XP is most helpful when...", "Requirements change constantly or the customer is unsure of the functionality", ["The requirements are fixed for years", "There is no customer", "The project is a one-time report"], "XP"),
    ("How many phases does XP have in the module?", "Six", ["Three", "Four", "Eight"], "XP phases"),
    ("In XP, stories are captured in which place during Analysis?", "The parking lot", ["The backlog vault", "The sprint board", "The test lab"], "XP Analysis"),
    ("Which XP phase includes small releases, regression testing, and demos and reviews?", "Wrapping", ["Planning", "Design", "Closure"], "XP phases"),
    ("Which XP phase includes pilot launch, training, and production support?", "Closure", ["Wrapping", "Execution", "Planning"], "XP phases"),
    ("What is a Story Cardboard in XP?", "A board of sticky notes that tracks the stories", ["A type of unit test", "A deployment tool", "A burn-down chart"], "XP storyboards"),
]

M4_NEW = [
    ("What is a model?", "A description where details are removed in a systematic manner and simplified", ["A fully detailed copy of a system", "A piece of source code", "A project schedule"], "Model definition"),
    ("Modeling a system means identifying its...", "Characteristics, states or statuses, and behavior using a notation", ["Programming language and database", "Budget and schedule", "Team members and roles"], "Modeling"),
    ("Which is NOT one of the four kinds of modeling in the module?", "Testing Modeling", ["Functional Modeling", "System Architecture", "Enterprise Modeling"], "Four kinds"),
    ("Functional modeling is a structured representation of what?", "Functions, activities, actions, processes, and operations in the system", ["Hardware prices", "User interface colors", "Network cables"], "Functional modeling"),
    ("Which is NOT a purpose of functional modeling?", "Choosing the programming language", ["Describing functions and processes", "Discovering information needs", "Establishing a basis for product and service costs"], "Functional modeling"),
    ("In a functional model, what does a PROCESS illustrate?", "Transformation from input to output", ["A collection of stored data", "The movement of data", "Something outside the system"], "Functional model elements"),
    ("In a functional model, a FLOW is shown by what?", "An arrow or flow line", ["A circle", "A rectangle with an open side", "A diamond"], "Functional model elements"),
    ("In a functional model, an EXTERNAL ENTITY is...", "External to the modeled system but interacts with it", ["A stored data collection", "A transformation of data", "A movement of data"], "Functional model elements"),
    ("A functional block diagram shows functions as what?", "Blocks", ["Arrows", "Tables", "Layers"], "Functional block diagram"),
    ("What does FFBD stand for?", "Functional Flow Block Diagram", ["Functional File Backup Diagram", "Fast Flow Business Diagram", "Final Function Build Design"], "FFBD"),
    ("An FFBD is best described as...", "A multi-tier, time-sequenced, step-by-step flow diagram", ["A single static list of requirements", "A database table", "A project calendar"], "FFBD"),
    ("System architecture is best described as...", "A conceptual model that defines the structure, behavior, and views of a system", ["A list of hardware prices", "A coding standard", "A test plan"], "Architecture"),
    ("A system architecture can consist of...", "Components and sub-systems that work together", ["Only one program", "Only hardware", "Only documents"], "Architecture"),
    ("Business process modeling is the activity of...", "Representing processes of an enterprise so they can be analyzed, improved, and automated", ["Writing source code", "Buying new servers", "Hiring staff"], "BPM"),
    ("Which is a typical business objective of business process modeling?", "Reduce cycle time or costs", ["Increase the number of meetings", "Remove all documentation", "Replace the customer"], "BPM"),
    ("How many types of business process does the module list?", "Three", ["Two", "Four", "Six"], "Process types"),
    ("Which business process type governs system operation, such as corporate governance?", "Management process", ["Operational process", "Supporting process", "Technical process"], "Process types"),
    ("Which business process type includes purchasing, manufacturing, marketing, and sales?", "Operational process", ["Management process", "Supporting process", "Strategic process"], "Process types"),
    ("Which business process type includes accounting and recruitment?", "Supporting process", ["Management process", "Operational process", "Core process"], "Process types"),
    ("What does BPMN stand for?", "Business Process Model and Notation", ["Basic Program Management Network", "Business Plan Management Notes", "Binary Process Mapping Notation"], "BPMN"),
    ("BPMN is drawn as what kind of diagram?", "A Business Process Diagram (BPD)", ["A Data Flow Diagram", "A Gantt chart", "A class diagram"], "BPMN"),
    ("Enterprise modeling represents what?", "The structure, processes, information, and resources of an organization", ["Only the programming code", "Only a single user's tasks", "Only network cables"], "Enterprise modeling"),
    ("Data modeling is a technique for defining what?", "Business requirements for a database", ["Network speeds", "User interface colors", "Employee salaries"], "Data modeling"),
    ("Which is part of a data model?", "Entity types, attributes, relationships, and integrity rules", ["Sprints and backlogs", "Gateways and tokens", "Servers and routers"], "Data modeling"),
    ("Which is NOT a design diagram listed in the module?", "Gantt chart", ["Data flow diagram", "Structured chart", "Decision tree"], "Design diagrams"),
    ("Design diagrams serve as a communications tool among which people?", "Engineers, designers, management, and programmers", ["Only customers", "Only the Scrum Master", "Only testers"], "Design diagram uses"),
    ("Which design diagram use gives a bird's-eye view without extra details?", "It provides an overview of the system", ["It defines roles", "It documents the system", "It facilitates troubleshooting"], "Design diagram uses"),
    ("Which design diagram use shows where data, forms, and reports are generated and who does what?", "It defines roles", ["It provides an overview", "It serves as a planning tool", "It promotes logical procedures"], "Design diagram uses"),
    ("Which design diagram use makes logic errors easier to see than in words?", "It promotes logical procedures", ["It defines roles", "It documents the system", "It serves as a communications tool"], "Design diagram uses"),
    ("A DFD is a graphic illustration of what?", "The flow of data and logic within a system", ["The hardware layout", "The project schedule", "The team structure"], "DFD"),
    ("In a DFD, the shape of the symbol tells the analyst what?", "Which operation is performed", ["How much it costs", "Who owns it", "When it is due"], "DFD"),
    ("In a DFD, what do the arrows show?", "The direction in which data flows", ["The cost of each step", "The size of the team", "The date of the project"], "DFD"),
    ("In a DFD, which symbol represents entities (input or output elements such as a person or place)?", "Rectangle", ["Rounded rectangle", "Arrow", "Open rectangle"], "DFD symbols"),
    ("In a DFD, processes are...", "Sequentially numbered", ["Always colored", "Always drawn as diamonds", "Never labeled"], "DFD symbols"),
    ("In a DFD, each data flow arrow should contain what?", "A data object", ["A person's name", "A date only", "A budget"], "DFD symbols"),
    ("A data flow in a DFD can carry which kind of data object?", "Forms, documents, or even verbal speech", ["Only electronic files", "Only money", "Only source code"], "DFD symbols"),
    ("What does an OPEN rectangle represent in a DFD?", "A data store", ["A process", "An entity", "A data flow"], "DFD symbols"),
    ("A MANUAL data store is shown as...", "A simple rectangle with an open end", ["An open rectangle with a vertical line near the closed end", "A circle", "A rounded rectangle"], "DFD symbols"),
    ("Which two DFD notations does the module name?", "Gane and Sarson, and Yourdon and DeMarco", ["Booch and Rumbaugh", "UML and BPMN", "Chen and Crow's Foot"], "DFD guidelines"),
    ("Which DFD guideline says to avoid showing both big-picture and detailed processes on one chart?", "Do not mix levels of detail on one chart", ["Use a template", "Desk check all diagrams", "Name and label all symbols"], "DFD guidelines"),
    ("Which DFD guideline says to check that every symbol is logically connected?", "Desk check all data flow diagrams", ["Use a template", "Correlate symbols with reference numbers", "Label the top of each diagram"], "DFD guidelines"),
    ("Which DFD guideline says to use reference numbers to relate symbols to other DFDs?", "Correlate symbols to other data flow diagrams", ["Desk check all diagrams", "Use a template", "Connect symbols with flow lines"], "DFD guidelines"),
    ("An arrowhead at EACH end of a flow line in a DFD shows what?", "Two-way flow of data", ["One-way flow of data", "An error", "A data store"], "DFD guidelines"),
    ("In the slide's production scheduling example, which is an external entity?", "Supplier", ["Production File", "Inventory File", "Estimating of Amount"], "DFD example"),
    ("In the slide's production scheduling example, which is a data store?", "Inventory File", ["Customer", "Supplier", "Production Department"], "DFD example"),
    ("What are the two sets of system requirements that most software defines?", "Minimum and recommended", ["Basic and premium", "Old and new", "Local and remote"], "System requirements"),
    ("What tends to happen to system requirements over time?", "They increase", ["They decrease", "They stay the same", "They disappear"], "System requirements"),
    ("Which is on the Typical Software Checklist?", "Minimum free storage space", ["Available ports", "Wireless connectivity", "Number of users"], "Checklists"),
    ("Which is on the Typical Hardware Checklist?", "Available ports (USB, Ethernet, etc.)", ["Minimum free storage space", "Minimum system memory (RAM)", "Audio hardware"], "Checklists"),
    ("Which requirement is NOT flexible between minimum and recommended?", "Disk space for installation", ["CPU", "GPU", "RAM"], "Requirements"),
    ("Requirements analysis starts with which first activity?", "The preliminary investigation", ["Writing code", "Deployment", "Testing"], "Requirements analysis"),
    ("Who performs requirements analysis, together with systems engineers or software developers?", "Requirements engineers and business analysts", ["Only end users", "Only testers", "Only marketing staff"], "Requirements analysis"),
    ("Which fact-finding technique is time consuming and reveals resistance to the new system?", "Interviews", ["Observation", "Research", "Questionnaires"], "Fact-finding"),
    ("Reports, bills, policy manuals, and regulations are used in which fact-finding technique?", "Record inspections (reviews)", ["Interviews", "Observation", "Closed questionnaires"], "Fact-finding"),
    ("Which fact-finding technique collects data from LARGE groups?", "Questionnaires", ["Interviews", "Observation", "Research"], "Fact-finding"),
    ("Open-ended questionnaires produce what kind of data?", "Qualitative", ["Quantitative", "Binary", "Numerical only"], "Fact-finding"),
    ("Which kind of questionnaire is costly because the questions must be printed?", "Closed-ended", ["Open-ended", "Verbal", "Online-only"], "Fact-finding"),
    ("Which fact-finding technique is described as an advanced one that checks facts in published materials?", "Research", ["Observation", "Interviews", "Closed questionnaires"], "Fact-finding"),
]
