"""SE1 (CS0025) Modules 3 and 4 items, written from the module slides.
Q = multiple choice / true-false, M = dropdown matching, L = typed list (enumeration)."""
from build_lib import L, M, Q

TF = ["False"]
TT = ["True"]

M3_Q = [
    Q("Which statement best describes Agile software development?", "Requirements and solutions evolve through collaboration",
      ["Development follows a fixed sequence with no changes", "Documentation must be completed before development begins", "Customers participate only after the product is completed"], "Ch. 1: What is Agile"),
    Q("Agile is built on the collaborative effort of which kind of teams?", "Self-organizing and cross-functional teams and their customers or end users",
      ["Separate departments that never meet", "Only managers", "Only external contractors"], "Ch. 1: What is Agile"),
    Q("Which of these does Agile advocate?", "Adaptive planning, evolutionary development, early delivery, and continual improvement",
      ["Fixed planning and one final release", "Documentation before any coding", "Avoiding change requests"], "Ch. 1: What is Agile"),
    Q("Scrum is a type of methodology under which approach?", "Agile", ["Waterfall", "Crystal only", "DSDM only"], "Ch. 1: What is Agile"),
    Q("Which is one of the Agile Development Values?", "Working software over comprehensive documentation",
      ["Processes and tools over individuals and interactions", "Contract negotiation over customer collaboration", "Following a plan over responding to change"], "Ch. 1: Agile values"),
    Q("Which Agile value says tools and processes are important, but competent people working together effectively matter more?", "Individuals and interactions over processes and tools",
      ["Working software over comprehensive documentation", "Customer collaboration over contract negotiation", "Responding to change over following a plan"], "Ch. 1: Agile values"),
    Q("Which Agile value says a plan is important but must not be too rigid?", "Responding to change over following a plan",
      ["Individuals and interactions over processes and tools", "Working software over comprehensive documentation", "Customer collaboration over contract negotiation"], "Ch. 1: Agile values"),
    Q("According to Agile principles, what is the primary measure of progress?", "Working software", ["Completed documentation", "Number of meetings", "Project budget"], "Ch. 1: Agile principles"),
    Q("Agile encourages teams to respond to changing requirements:", "Even late in development", ["Only before development starts", "Only during planning", "Never after requirements are approved"], "Ch. 1: Agile principles"),
    Q("According to the Agile principles, how often should working software be delivered?", "Frequently, in weeks rather than months", ["Once a year", "Only at the end of the project", "Every few years"], "Ch. 1: Agile principles"),
    Q("Which is the best form of communication according to the Agile principles?", "Face-to-face conversation (co-location)", ["Email only", "Formal written reports", "Contracts"], "Ch. 1: Agile principles"),
    Q("Which Agile principle says the best architectures, requirements, and designs come from which kind of teams?", "Self-organizing teams", ["Large management teams", "Outsourced teams", "Teams with fixed roles only"], "Ch. 1: Agile principles"),
    Q("Which Agile principle calls simplicity essential?", "Simplicity is the art of maximizing the amount of work not done", ["Do all possible work in advance", "Document everything", "Add every requested feature"], "Ch. 1: Agile principles"),
    Q("Agile breaks product development work into what?", "Small increments that minimize up-front planning and design", ["One large phase", "Separate models that never combine", "Yearly releases"], "Ch. 1: What is Agile"),
    Q("Which characteristic distinguishes Agile from the Waterfall model?", "Agile uses an incremental and iterative approach", ["Agile follows only one development phase", "Agile discourages customer involvement", "Agile requires all requirements to remain unchanged"], "Ch. 1: Agile vs Waterfall"),
    Q("In which model can the customer only see the product at the end of the project?", "Waterfall", ["Agile", "Scrum", "Crystal"], "Ch. 1: Agile vs Waterfall"),
    Q("In which model is testing done only after the development phase?", "Waterfall", ["Agile", "Scrum", "XP"], "Ch. 1: Agile vs Waterfall"),
    Q("How long are Agile iterations, according to the comparison table?", "Short, about 2 to 4 weeks", ["6 to 12 months", "One day", "Exactly one year"], "Ch. 1: Agile vs Waterfall"),
    Q("Which model gives documentation top priority?", "Waterfall", ["Agile", "Scrum", "Lean"], "Ch. 1: Agile vs Waterfall"),
    Q("In Agile, how do testers and developers work?", "Together, with user acceptance at the end of every sprint", ["Separately, with acceptance at the end of the project", "Testers only after release", "Developers only"], "Ch. 1: Agile vs Waterfall"),
    Q("Scrum is designed for teams of how many members?", "Ten or fewer", ["Exactly three", "At least twenty", "Any size, with no limit"], "Ch. 1: Scrum"),
    Q("Scrum work is broken into timeboxed iterations called what?", "Sprints", ["Phases", "Releases", "Cycles"], "Ch. 1: Scrum"),
    Q("What is the longest a sprint can be, and the most common length?", "No longer than a month; two weeks is most common", ["One day; one hour", "Three months; six weeks", "One year; six months"], "Ch. 1: Scrum"),
    Q("Which is a benefit of Scrum listed in the module?", "Flexibility and adaptability", ["Fewer team members", "No planning", "No customer feedback"], "Ch. 1: Scrum benefits"),
    Q("Which Scrum role is the facilitator of the scrum development process?", "Scrum Master", ["Product Owner", "Development Team", "Stakeholder"], "Ch. 1: Scrum roles"),
    Q("Which Scrum role represents the stakeholders and administers the scrum backlog?", "Product Owner", ["Scrum Master", "Development Team", "Tester"], "Ch. 1: Scrum roles"),
    Q("Which Scrum role removes impediments to sprints and coaches and motivates the team?", "Scrum Master", ["Product Owner", "Development Team", "Customer"], "Ch. 1: Scrum roles"),
    Q("How large is the scrum development team?", "Three to ten individuals", ["One to two", "Eleven to twenty", "Twenty or more"], "Ch. 1: Scrum roles"),
    Q("Which Scrum role prioritizes goals for each sprint based on their value to stakeholders?", "Product Owner", ["Scrum Master", "Development Team", "Tester"], "Ch. 1: Scrum roles"),
    Q("What does each sprint start with?", "A sprint planning event that establishes a sprint goal", ["A sprint review", "A retrospective", "A release"], "Ch. 1: Scrum events"),
    Q("How long is sprint planning for a 2-week sprint?", "Four hours", ["Fifteen minutes", "Two hours", "One and a half hours"], "Ch. 1: Sprint planning"),
    Q("How long is the daily scrum?", "Fifteen minutes (timeboxed)", ["One hour", "Four hours", "Two hours"], "Ch. 1: Daily scrum"),
    Q("Which is one of the three questions in the daily scrum?", "Do I see any impediment that could prevent me or the team from meeting our sprint goal?", ["What is the budget?", "Who will be fired?", "Which customer is unhappy?"], "Ch. 1: Daily scrum"),
    Q("How long is the sprint review for a two-week sprint?", "Two hours", ["Fifteen minutes", "Four hours", "One and a half hours"], "Ch. 1: Sprint review"),
    Q("Which statement about the sprint review is correct?", "Incomplete work cannot be demonstrated", ["Incomplete work must be demonstrated", "It is facilitated by the customer only", "It happens before the sprint starts"], "Ch. 1: Sprint review"),
    Q("How long is the sprint retrospective for a two-week sprint?", "One and a half hours", ["Fifteen minutes", "Four hours", "Two hours"], "Ch. 1: Sprint retrospective"),
    Q("Who facilitates the sprint retrospective?", "The Scrum Master", ["The Product Owner", "The customer", "The tester"], "Ch. 1: Sprint retrospective"),
    Q("What is the backlog refinement formerly called?", "Grooming", ["Planning", "Review", "Retrospective"], "Ch. 1: Backlog refinement"),
    Q("Which Agile methodology focuses primarily on people and their interactions rather than processes and tools?", "Crystal Methodology", ["DSDM", "FDD", "Waterfall"], "Ch. 2: Crystal"),
    Q("Who developed the Crystal Methodology?", "Alistair Cockburn", ["Kent Beck", "Ken Schwaber", "Mary Poppendieck"], "Ch. 2: Crystal"),
    Q("Which sequence correctly represents the three phases of Crystal Methodology?", "Chartering, Cyclic Delivery, Wrap Up", ["Planning, Coding, Testing", "Analysis, Design, Deployment", "Feasibility, Development, Maintenance"], "Ch. 2: Crystal phases"),
    Q("In Crystal, in which phase is a development team created and a preliminary feasibility analysis performed?", "Chartering", ["Cyclic Delivery", "Wrap Up", "Deployment"], "Ch. 2: Crystal phases"),
    Q("In Crystal, in which phase does the integrated product get delivered to real users through delivery cycles?", "Cyclic Delivery", ["Chartering", "Wrap Up", "Feasibility"], "Ch. 2: Crystal phases"),
    Q("In Crystal, in which phase are deployment into the user environment and post-deployment reviews performed?", "Wrap Up", ["Chartering", "Cyclic Delivery", "Planning"], "Ch. 2: Crystal phases"),
    Q("What does DSDM require of its users?", "Users must be actively involved, and teams are empowered to make decisions", ["Users stay away from the team", "Users approve only at the end", "Users write the code"], "Ch. 2: DSDM"),
    Q("Which DSDM technique completes a project incrementally by splitting it into portions, each with a fixed budget and delivery date?", "Timeboxing", ["MoSCoW", "Prototyping", "Chartering"], "Ch. 2: DSDM techniques"),
    Q("In timeboxing, what happens to the requirements if time or money runs out?", "The lowest priority requirements are omitted", ["The deadline is extended", "The budget is doubled", "All requirements are dropped"], "Ch. 2: Timeboxing"),
    Q("What is MoSCoW used for?", "Prioritizing requirements with stakeholders", ["Scheduling meetings", "Writing code", "Testing"], "Ch. 2: MoSCoW"),
    Q("What does the M in MoSCoW stand for?", "Must have", ["Maybe", "Minimum", "Maintain"], "Ch. 2: MoSCoW"),
    Q("What does the W in MoSCoW stand for?", "Won't have", ["Will have", "Wait", "Work"], "Ch. 2: MoSCoW"),
    Q("Which DSDM technique creates early versions of the system so users can test-drive it?", "Prototyping", ["Timeboxing", "MoSCoW", "Chartering"], "Ch. 2: Prototyping"),
    Q("Which is the first phase of DSDM?", "Pre-project", ["Feasibility Study", "Implementation", "Post-project"], "Ch. 2: DSDM phases"),
    Q("Which is the last phase of DSDM?", "Post-project", ["Pre-project", "Implementation", "Feasibility Study"], "Ch. 2: DSDM phases"),
    Q("Feature Driven Development (FDD) is focused around what?", "Designing and building features", ["Pair programming", "Timeboxing", "Daily scrums"], "Ch. 2: FDD"),
    Q("Which is part of FDD's short phases of work per feature?", "Domain walkthrough, design inspection, promote to build, code inspection, design", ["Sprint review", "Chartering", "Story cardboard"], "Ch. 2: FDD"),
    Q("Lean software development is adapted from which system?", "The Toyota Production System", ["The Waterfall model", "The Scrum guide", "The Agile Manifesto"], "Ch. 2: Lean"),
    Q("Lean is based on which principle?", "Just in time production", ["Fixed scope, fixed time", "Documentation first", "Big bang release"], "Ch. 2: Lean"),
    Q("Which Lean principle says if an activity could be bypassed or the result achieved without it, it is waste?", "Eliminating Waste", ["Amplifying Learning", "Defer Commitment", "Early Delivery"], "Ch. 2: Lean principles"),
    Q("Which Lean principle says to delay decisions until they can be made on facts rather than assumptions?", "Defer Commitment", ["Early Delivery", "Building Integrity", "Empowering the Team"], "Ch. 2: Lean principles"),
    Q("Which Lean principle says that software value is measured in fitness for use, not conformance to requirements?", "Amplifying Learning", ["Eliminating Waste", "Early Delivery", "Optimize the Whole"], "Ch. 2: Lean principles"),
    Q("Which Lean principle says the sooner the product is delivered without major defects, the sooner feedback comes?", "Early Delivery", ["Defer Commitment", "Building Integrity", "Eliminating Waste"], "Ch. 2: Lean principles"),
    Q("Which Lean principle follows the Agile principle 'build projects around motivated individuals and trust them'?", "Empowering the Team", ["Optimize the Whole", "Building Integrity", "Defer Commitment"], "Ch. 2: Lean principles"),
    Q("Which Lean principle refers to the customer's overall experience of the system?", "Building Integrity", ["Amplifying Learning", "Early Delivery", "Eliminating Waste"], "Ch. 2: Lean principles"),
    Q("Which Lean phrase appears in the module?", "Think big, act small, fail fast; learn rapidly", ["Plan once, build once", "Move slow, document everything", "Build big, ship late"], "Ch. 2: Lean"),
    Q("Extreme Programming (XP) is very helpful when what is true?", "Customer demands or requirements constantly change", ["Requirements never change", "There is no customer", "The project has a fixed contract"], "Ch. 2: XP"),
    Q("XP advocates what kind of releases?", "Frequent releases in short development cycles", ["One yearly release", "No releases", "Only beta releases"], "Ch. 2: XP"),
    Q("Which is the first XP phase in the module?", "Planning", ["Closure", "Wrapping", "Execution"], "Ch. 2: XP phases"),
    Q("In which XP phase are stories captured in the 'Parking lot' and prioritized?", "Analysis", ["Planning", "Design", "Closure"], "Ch. 2: XP phases"),
    Q("In which XP phase does coding and unit testing happen?", "Execution", ["Planning", "Wrapping", "Closure"], "Ch. 2: XP phases"),
    Q("In which XP phase do pilot launch, training, and production launch happen?", "Closure", ["Planning", "Analysis", "Wrapping"], "Ch. 2: XP phases"),
    Q("Which tool collects XP stories on sticky notes on a board?", "Story Cardboard", ["Online Storyboard only", "Backlog refinement", "Timebox"], "Ch. 2: XP tools"),
    Q("Agile emphasizes individuals and interactions over processes and tools.", "True", TF, "Ch. 1: Agile values"),
    Q("Agile considers comprehensive documentation more important than working software.", "False", TT, "Ch. 1: Agile values"),
    Q("Scrum is a type of methodology under Agile.", "True", TF, "Ch. 1: What is Agile"),
    Q("Crystal was developed by Kent Beck.", "False", TT, "Ch. 2: Crystal (Alistair Cockburn)"),
    Q("A sprint review can demonstrate incomplete work.", "False", TT, "Ch. 1: Sprint review"),
]

M3_L = [
    L("List the four Agile Development Values.", ["Individuals and interactions over processes and tools", "Working software over comprehensive documentation", "Customer collaboration over contract negotiation", "Responding to change over following a plan"], "Ch. 1: Agile values"),
    L("List the three Scrum roles.", ["Scrum Master", "Product Owner", "Scrum Development Team"], "Ch. 1: Scrum roles"),
    L("List the six Scrum events.", ["Sprint", "Sprint Planning", "Daily Scrum", "Sprint Review", "Sprint Retrospective", "Backlog Refinement"], "Ch. 1: Scrum events", ordered=True),
    L("List the three questions asked in the daily scrum.", ["What did I complete yesterday that contributed to the sprint goal?", "What do I plan to complete today to contribute to the sprint goal?", "Do I see any impediment that could prevent me or the team from meeting the sprint goal?"], "Ch. 1: Daily scrum"),
    L("List the three questions asked in the sprint retrospective.", ["What went well during the sprint?", "What did not go well?", "What could be improved for better productivity in the next sprint?"], "Ch. 1: Sprint retrospective"),
    L("List the three phases of Crystal Methodology.", ["Chartering", "Cyclic Delivery", "Wrap Up"], "Ch. 2: Crystal", ordered=True),
    L("List the seven phases of DSDM.", ["Pre-project", "Feasibility Study", "Business Study", "Functional Model Iteration", "Design and Build Iteration", "Implementation", "Post-project"], "Ch. 2: DSDM phases", ordered=True),
    L("List the four MoSCoW categories.", ["Must have", "Should have", "Could have", "Won't have"], "Ch. 2: MoSCoW", ordered=True),
    L("List the seven principles of Lean software development.", ["Eliminating Waste", "Amplifying Learning", "Defer Commitment", "Early Delivery", "Empowering the Team", "Building Integrity", "Optimize the Whole"], "Ch. 2: Lean principles", ordered=True),
    L("List the six phases of Extreme Programming (XP).", ["Planning", "Analysis", "Design", "Execution", "Wrapping", "Closure"], "Ch. 2: XP phases", ordered=True),
    L("List the four things that happen in each Crystal Cyclic Delivery cycle.", ["Team updates and refines the release plan", "Implements a subset of the requirements through one or more program test integrate iterations", "Integrated product is delivered to real users", "Review of the project plan and adopted development methodology"], "Ch. 2: Crystal cyclic delivery", ordered=True),
    L("List any four of the eight FDD practices.", ["Domain Object Modeling", "Development by Feature", "Component/Class Ownership", "Feature Teams", "Inspections", "Configuration Management", "Regular Builds", "Visibility of progress and results"][:4], "Ch. 2: FDD (eight practices: also Inspections, Configuration Management, Regular Builds, Visibility of progress and results)"),
]

M3_M = [
    M("Match the Scrum item with its time or size.", [("Daily scrum", "15 minutes"), ("Sprint planning (2-week sprint)", "4 hours"), ("Sprint review (2-week sprint)", "2 hours"), ("Sprint retrospective (2-week sprint)", "1.5 hours"), ("Scrum team", "3 to 10 people")], ["30 minutes", "1 day"], "Ch. 1: Scrum events"),
    M("Match the Agile method with its focus.", [("Crystal", "People and their interactions"), ("DSDM", "Timeboxing and active user involvement"), ("FDD", "Designing and building features"), ("Lean", "Eliminating waste"), ("XP", "Frequent releases in short cycles")], ["Fixed requirements"], "Ch. 2 methods"),
    M("Match the Lean principle with its description.", [("Eliminating Waste", "Bypass any activity whose result can be achieved without it"), ("Defer Commitment", "Delay decisions until they rest on facts"), ("Early Delivery", "Deliver sooner to get feedback sooner"), ("Empowering the Team", "Trust motivated individuals to get the job done"), ("Optimize the Whole", "Find and remove the root causes of defects")], ["Document everything first"], "Ch. 2: Lean principles"),
    M("Match the Scrum role with its responsibility.", [("Scrum Master", "Facilitates the process and removes impediments"), ("Product Owner", "Represents stakeholders and administers the backlog"), ("Scrum team", "Self-organized group that does the actual work")], ["Approves the budget"], "Ch. 1: Scrum roles"),
    M("Match the model with its description.", [("Agile", "Incremental and iterative; customer sees the product early"), ("Waterfall", "Flows sequentially; customer sees the product at the end")], ["Only used for small hardware"], "Ch. 1: Agile vs Waterfall"),
]

M4_Q = [
    Q("What is a model in systems development?", "A simplified description of a system", ["A complete copy of an existing system", "A collection of programming codes", "A list of hardware components"], "Ch. 1: System models"),
    Q("What does modeling a system mean?", "Identifying its characteristics, states, and behavior using a notation", ["Buying hardware", "Writing the final code", "Deleting old files"], "Ch. 1: System models"),
    Q("What does systems modeling use to conceptualize and construct systems?", "Models and diagrams", ["Programming languages only", "Financial statements", "Marketing plans"], "Ch. 1: System models"),
    Q("Which of these is one of the system modeling types in the module?", "Enterprise Modeling", ["Hardware Modeling", "Marketing Modeling", "Cost Modeling"], "Ch. 1: System models"),
    Q("Which modeling approach represents the functions, activities, and operations within a system?", "Functional modeling", ["Enterprise modeling", "Data modeling", "Financial modeling"], "Ch. 1: Functional modeling"),
    Q("What does a functional modeling perspective concentrate on?", "Describing the dynamic process", ["Storing data only", "Organizational charts", "Hardware cost"], "Ch. 1: Functional modeling"),
    Q("In functional modeling, which element illustrates the transformation of input into output?", "Process", ["Data store", "External entity", "Flow line"], "Ch. 1: Functional modeling"),
    Q("In functional modeling, which element is data-collection or some material, shown as a rectangle with the right side usually open?", "Store", ["Process", "Flow", "External entity"], "Ch. 1: Functional modeling"),
    Q("In functional modeling, which element is the movement of data or material, shown as an arrow?", "Flow", ["Store", "Process", "External entity"], "Ch. 1: Functional modeling"),
    Q("In functional modeling, which element is outside the modeled system but interacts with it?", "External entity", ["Process", "Store", "Flow"], "Ch. 1: Functional modeling"),
    Q("What does a functional block diagram describe?", "The functions and interrelationships of a system", ["Only the database tables", "Employee records", "Hardware prices"], "Ch. 1: Functional block diagram"),
    Q("What does a Functional Flow Block Diagram (FFBD) primarily present?", "Time-sequenced functional activities", ["Database table relationships", "Hardware prices", "Employee records"], "Ch. 1: FFBD"),
    Q("What is system architecture?", "A conceptual model of a system's structure and behavior", ["A list of users who can access a system", "A financial plan for system development", "A collection of programming errors"], "Ch. 1: System architecture"),
    Q("What can a system architecture consist of?", "System components and the sub-systems that work together", ["Only the user interface", "Only the database", "Only hardware"], "Ch. 1: System architecture"),
    Q("What is the primary purpose of Business Process Modeling (BPM)?", "To represent, analyze, and improve organizational processes", ["To identify computer specifications", "To determine employee salaries", "To install software applications"], "Ch. 1: BPM"),
    Q("What is a common business objective of BPM?", "Increase process speed, increase quality, or reduce costs", ["Increase paperwork", "Reduce customers", "Increase cycle time"], "Ch. 1: BPM"),
    Q("What is a business process?", "A collection of related, structured activities to produce a specific service or product for a customer", ["A list of hardware", "A programming language", "A random set of tasks"], "Ch. 1: Business process"),
    Q("Which type of business process creates the organization's primary value stream?", "Operational process", ["Management process", "Supporting process", "Documentation process"], "Ch. 1: Business process types"),
    Q("Which type of business process governs system operation, including corporate governance and strategic management?", "Management process", ["Operational process", "Supporting process", "Documentation process"], "Ch. 1: Business process types"),
    Q("Which of the following is an example of a supporting process?", "Recruitment and technical support", ["Strategic management", "Product manufacturing", "Marketing and sales"], "Ch. 1: Business process types"),
    Q("What is the purpose of Business Process Model and Notation (BPMN)?", "To provide a graphical notation for business processes", ["To identify computer hardware", "To calculate software costs", "To create database records"], "Ch. 1: BPMN"),
    Q("In BPMN, business processes are specified in which diagram?", "Business Process Diagram (BPD)", ["Data Flow Diagram", "Entity Diagram", "Gantt Chart"], "Ch. 1: BPMN"),
    Q("What is a business model?", "A framework for creating economic, social, or other forms of value", ["A type of database", "A programming pattern", "A network diagram"], "Ch. 1: Business model"),
    Q("What is enterprise modeling?", "Representing the structure, processes, information, and resources of a large organization", ["Modeling only a single function", "Writing code for enterprises", "Buying software"], "Ch. 1: Enterprise modeling"),
    Q("Data modeling is used for what?", "Defining business requirements for a database", ["Designing hardware", "Writing test cases", "Scheduling sprints"], "Ch. 1: Data modeling"),
    Q("Which of the following is normally part of a data model?", "Entity types, attributes, relationships, integrity rules, and definitions", ["Only screenshots", "Sprint backlogs", "Story cards"], "Ch. 1: Data modeling"),
    Q("Which of these is a design diagram named in the module?", "Data flow diagram", ["Sprint diagram", "Backlog chart", "Story cardboard"], "Ch. 1: Design diagrams"),
    Q("Which purpose of a design diagram means it is a convenient way to communicate ideas among engineers, designers, and management?", "It serves as a communications tool", ["It serves as a planning tool", "It documents the system", "It facilitates troubleshooting"], "Ch. 1: Design diagram purposes"),
    Q("Which purpose of a design diagram means it acts as a blueprint of the inner workings when diagnosing a failure?", "It facilitates troubleshooting", ["It defines roles", "It provides an overview", "It documents the system"], "Ch. 1: Design diagram purposes"),
    Q("What does a data flow diagram (DFD) illustrate?", "The flow of data and logic within a system", ["Hardware cabling only", "Employee schedules", "Source code"], "Ch. 1: DFD"),
    Q("In a DFD, which symbol denotes input and output elements such as a person or place?", "Rectangle (entity)", ["Rounded rectangle", "Arrow", "Open rectangle"], "Ch. 1: DFD symbols"),
    Q("In a DFD, activities and operations are represented by what?", "A rounded rectangle (sometimes a circle), sequentially numbered", ["A rectangle with an open end", "An arrow", "A diamond"], "Ch. 1: DFD symbols"),
    Q("In a DFD, data flow is represented by what?", "An arrow containing a data object", ["A circle", "A rectangle", "An open rectangle"], "Ch. 1: DFD symbols"),
    Q("In a DFD, data stores are represented by what?", "An open rectangle", ["A rounded rectangle", "An arrow", "A circle"], "Ch. 1: DFD symbols"),
    Q("How is a manual data store shown in a DFD?", "A simple rectangle with an open end", ["A circle", "An arrow", "A rounded rectangle"], "Ch. 1: DFD symbols"),
    Q("How is an automated data store shown in a DFD?", "An open rectangle with an additional vertical line near the closed end", ["A rounded rectangle", "A diamond", "A circle"], "Ch. 1: DFD symbols"),
    Q("Which DFD guideline is correct?", "Do not mix levels of detail on one chart", ["Mix all levels in one chart", "Use both notations at once", "Leave symbols unlabeled"], "Ch. 1: DFD guidelines"),
    Q("Which pair of notations can be used for DFDs?", "Gane & Sarson or Yourdon & DeMarco", ["UML and BPMN", "ER and IDEF", "Chen and Crow's Foot"], "Ch. 1: DFD guidelines"),
    Q("Which DFD guideline says to check that every symbol is logically connected?", "Desk check all data flow diagrams", ["Use a template", "Label the top", "Use only one symbol"], "Ch. 1: DFD guidelines"),
    Q("What should be labeled at the top of each data flow diagram?", "System name, date prepared, and the name of the preparer", ["Only the date", "Only the customer", "Nothing"], "Ch. 1: DFD guidelines"),
    Q("What are system requirements?", "The required specifications a device must have to use certain hardware or software", ["Only the price of software", "A list of users", "A legal document"], "Ch. 2: System requirements"),
    Q("Most software defines which two sets of system requirements?", "Minimum and recommended", ["Basic and advanced", "Free and paid", "Old and new"], "Ch. 2: System requirements"),
    Q("Which system requirement is not flexible?", "The operating system and disk space needed for installation", ["CPU speed", "GPU", "RAM"], "Ch. 2: System requirements"),
    Q("What does requirements analysis encompass?", "The tasks of investigating, scoping, and defining a new or altered system", ["Only writing code", "Only testing", "Only maintenance"], "Ch. 2: Requirements analysis"),
    Q("What is the first activity of requirements analysis?", "The preliminary investigation", ["Coding", "Deployment", "Testing"], "Ch. 2: Requirements analysis"),
    Q("Which technique can analysts use to collect information about the current system from potential users, but is time consuming?", "Interviews", ["Observation", "Research", "Record inspections"], "Ch. 2: Fact finding"),
    Q("Which fact finding technique uses reports, bills, policy manuals, regulations, and standard operating procedures?", "Record inspections or reviews", ["Interviews", "Questionnaires", "Observation"], "Ch. 2: Fact finding"),
    Q("Which fact finding technique collects data from large groups?", "Questionnaires", ["Interviews", "Observation", "Research"], "Ch. 2: Fact finding"),
    Q("Which questionnaire type is qualitative and answered in the respondent's own words?", "Open-ended", ["Closed-ended", "Multiple choice", "Yes or no"], "Ch. 2: Questionnaires"),
    Q("Which questionnaire type uses prescribed answers and generates quantitative results?", "Closed-ended", ["Open-ended", "Essay", "Oral"], "Ch. 2: Questionnaires"),
    Q("Which fact finding technique is a skill where analysts identify the right information, person, and place?", "Observation", ["Interviews", "Questionnaires", "Research"], "Ch. 2: Fact finding"),
    Q("Which advanced fact finding technique obtains information from published materials to verify facts?", "Research", ["Observation", "Interviews", "Questionnaires"], "Ch. 2: Fact finding"),
    Q("An operating system is a system requirement for a computer.", "True", TF, "Ch. 2: System requirements"),
    Q("A design diagram is a communications tool and a planning tool.", "True", TF, "Ch. 1: Design diagram purposes"),
    Q("Interviews are quick and cheap for collecting information.", "False", TT, "Ch. 2: Interviews are time consuming"),
]

M4_L = [
    L("List the four types of system modeling in the module.", ["Functional Modeling", "System Architecture", "Business Process Modeling", "Enterprise Modeling"], "Ch. 1: System models", ordered=True),
    L("List the four elements of a functional model.", ["Process", "Store", "Flow", "External Entity"], "Ch. 1: Functional modeling"),
    L("List the three types of business process.", ["Management Process", "Operational Process", "Supporting Process"], "Ch. 1: Business process types", ordered=True),
    L("List the four DFD symbols.", ["Entity (rectangle)", "Process (rounded rectangle or circle)", "Data flow (arrow)", "Data store (open rectangle)"], "Ch. 1: DFD symbols"),
    L("List the five fact finding techniques.", ["Interviews", "Record inspections or reviews", "Questionnaires", "Observation", "Research"], "Ch. 2: Fact finding"),
    L("List the two types of questionnaires.", ["Open-ended", "Closed-ended"], "Ch. 2: Questionnaires"),
    L("List the two sets of system requirements.", ["Minimum", "Recommended"], "Ch. 2: System requirements"),
    L("List any four design diagrams named in the module.", ["Data flow diagrams", "Structured charts", "Decision trees", "Block diagrams (cycle of operations)"], "Ch. 1: Design diagrams"),
    L("List any four purposes of a design diagram.", ["Communications tool", "Planning tool", "Provides an overview of the system", "Defines roles"], "Ch. 1: Design diagram purposes (eight in total: also demonstrates relationships, promotes logical procedures, facilitates troubleshooting, documents the system)"),
    L("List the two DFD notations.", ["Gane & Sarson", "Yourdon & DeMarco"], "Ch. 1: DFD guidelines"),
    L("List the four components of a data model.", ["Entity types", "Attributes", "Relationships", "Integrity rules"], "Ch. 1: Data modeling"),
]

M4_M = [
    M("Match the DFD symbol with its shape.", [("Entity", "Rectangle"), ("Process", "Rounded rectangle or circle"), ("Data flow", "Arrow"), ("Data store", "Open rectangle")], ["Diamond"], "Ch. 1: DFD symbols"),
    M("Match the business process type with its example.", [("Management process", "Corporate governance and strategic management"), ("Operational process", "Purchasing, manufacturing, marketing, sales"), ("Supporting process", "Accounting, recruitment, technical support")], ["Software testing only"], "Ch. 1: Business process types"),
    M("Match the fact finding technique with its description.", [("Interviews", "Discover misunderstandings and resistance; time consuming"), ("Record inspections", "Reports, bills, policy manuals, procedures"), ("Questionnaires", "Data from large groups; open or closed"), ("Observation", "Choose the right person and place to watch"), ("Research", "Published materials used to verify facts")], ["Guessing"], "Ch. 2: Fact finding"),
    M("Match the modeling type with its description.", [("Functional modeling", "Functions, activities, and operations of a system"), ("System architecture", "Conceptual model of structure and behavior"), ("Business process modeling", "Represents processes so they can be analyzed and improved"), ("Data modeling", "Defines business requirements for a database")], ["Modeling of hardware prices"], "Ch. 1"),
    M("Match the questionnaire type with its property.", [("Open-ended", "Qualitative; answers in own words"), ("Closed-ended", "Quantitative; prescribed answers")], ["Oral only"], "Ch. 2: Questionnaires"),
]
