"""Curated card sets. AndyHub-generated cards are kept by id; new slide-literal cards are added.
Card = (question, correct, [three wrong], why)."""

KEEP_M3 = [3, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 27, 30, 31, 32, 33, 34, 35, 36, 38, 40]
KEEP_M4 = [41, 42, 43, 45, 46, 47, 48, 51, 52, 53, 54, 55, 57, 58, 61, 63, 64, 65, 66, 69, 70, 71, 79]
KEEP_MOCK = [83, 85, 88, 89, 90, 91, 92, 93, 95, 97, 98, 99, 100, 101, 102, 104, 109, 113, 114, 116, 118, 119,
             121, 123, 125, 126, 127, 129, 130]

M3_NEW = [
    ("How many phases does the SDLC have in the Module 3 slides?", "Six", ["Four", "Five", "Seven"], "SDLC slide"),
    ("Which SDLC phase ends with the Software Requirement Specification (SRS) document?", "Requirements and Analysis", ["Design", "Implementation", "Testing"], "Requirements and Analysis phase"),
    ("Which SDLC phase ends with High-Level Design (HLD) and Low-Level Design (LLD) documents?", "Design", ["Requirements and Analysis", "Implementation", "Deployment"], "Design phase"),
    ("Which SDLC phase is the longest of the life cycle?", "Implementation", ["Design", "Testing", "Maintenance"], "Implementation phase"),
    ("In which SDLC phase does the product manager release the final software to end users?", "Deployment", ["Testing", "Maintenance", "Implementation"], "Deployment phase"),
    ("Which SDLC phase includes supporting customers, fixing bugs found in production, and gathering new customer requests?", "Maintenance", ["Deployment", "Testing", "Design"], "Maintenance phase"),
    ("Each SDLC phase takes its input from what?", "The results of the previous phase", ["The customer's budget", "The next phase", "The programming language chosen"], "SDLC slide"),
    ("Which are the three most popular software development methodologies in the module?", "Waterfall, Agile, and Lean", ["Waterfall, Scrum, and XP", "Agile, FDD, and XP", "Lean, DSDM, and Crystal"], "Software Development Methodologies"),
    ("The type of methodology to use depends on which factors?", "Type of project, length of project, and size of team", ["Cost of hardware only", "Programming language only", "Number of customers only"], "Software Development Methodologies"),
    ("Who created the original waterfall model?", "Winston W. Royce", ["Roy Fielding", "Alistair Cockburn", "Erich Gamma"], "Waterfall slide"),
    ("How many software developers wrote the Agile Manifesto, and in what year?", "17 developers in 2001", ["12 developers in 1994", "7 developers in 2001", "23 developers in 2020"], "Agile slide"),
    ("How many principles does the Agile Manifesto list?", "12", ["4", "7", "23"], "Agile slide"),
    ("How long is a sprint usually, according to the module?", "2 to 4 weeks", ["1 to 2 days", "6 to 8 weeks", "Exactly 15 minutes"], "Agile Methods slide"),
    ("In Agile, what is the backlog?", "A prioritized list of all the features of the software", ["A list of resolved bugs", "A time-boxed period of development", "A daily stand-up meeting"], "Agile Methods slide"),
    ("Which template does the module suggest for a user story?", "As a <user|role>, I would like to <action>, so that <value|benefit>", ["Given <state>, when <event>, then <result>", "The system shall <requirement>", "If <condition>, then <action>, else <action>"], "Agile Methods slide"),
    ("What is the largest recommended size for a scrum team?", "10 individuals", ["3 individuals", "15 individuals", "25 individuals"], "Scrum Teams slide"),
    ("How long should the scrum master's daily stand-up meeting last at most?", "15 minutes", ["5 minutes", "30 minutes", "1 hour"], "Scrum Teams slide"),
    ("Which Agile method emphasizes eliminating wasted effort and reducing programmer cognitive load?", "Lean", ["Scrum", "Extreme Programming", "Feature-Driven Development"], "Agile Methods slide"),
    ("Which Agile method prescribes development feature by feature from an overall model?", "Feature-Driven Development (FDD)", ["Scrum", "Lean", "Extreme Programming (XP)"], "Agile Methods slide"),
    ("Which Lean principle is described as the most fundamental?", "Eliminate waste", ["Amplify learning", "Optimize the whole", "Empower the team"], "Lean slide"),
    ("Which is NOT one of the seven wastes of software development in the module?", "Refactoring", ["Partially done work", "Task switching", "Defects"], "Lean: eliminate waste"),
    ("Why does Lean say to decide as late as possible when there is uncertainty?", "Decisions should be based on facts rather than opinions or speculation", ["To avoid ever making decisions", "To let customers make all decisions", "To reduce the number of sprints"], "Lean slide"),
    ("Which Lean principle says each person must be allowed to make decisions in their own area of expertise?", "Empower the team", ["Build integrity in", "Optimize the whole", "Deliver as fast as possible"], "Lean slide"),
    ("Which Lean principle says software must be built cohesively and not only by each expert's own focus?", "Optimize the whole", ["Empower the team", "Amplify learning", "Decide as late as possible"], "Lean slide"),
    ("Who are the Gang of Four (GoF) authors known for?", "Design Patterns: Elements of Reusable Object-Oriented Software (1994)", ["The Agile Manifesto (2001)", "The REST architectural style", "Lean Software Development"], "Software Design Patterns"),
    ("Into which three categories did the Gang of Four divide their patterns?", "Creational, Structural, Behavioral", ["Model, View, Controller", "Local, Centralized, Distributed", "Functional, Non-functional, Integration"], "Original Design Patterns"),
    ("How many design patterns did the Gang of Four list?", "23", ["7", "12", "50"], "Original Design Patterns"),
    ("The Observer design pattern belongs to which category?", "Behavioral", ["Creational", "Structural", "Architectural"], "Original Design Patterns"),
    ("What must the subject in the Observer pattern be able to do?", "Store a list of its observers and add or remove them", ["Poll each observer for changes", "Store no data at all", "Only send data once"], "Observer slide"),
    ("Which MVC component is the application's data structure that manages the data, logic, and rules?", "Model", ["View", "Controller", "Router"], "MVC slide"),
    ("Which MVC component is the visual representation of the data?", "View", ["Model", "Controller", "Database"], "MVC slide"),
    ("What is the benefit of MVC stated in the module?", "Each component can be built in parallel", ["It removes the need for a database", "It requires only one developer", "It replaces version control"], "MVC slide"),
    ("Which is NOT a benefit of version control in the module?", "Faster hardware performance", ["Enables collaboration", "Accountability and visibility", "Work in isolation"], "Version Control Systems"),
    ("Which version control type stores the delta between two versions of a file in a simple database?", "Local (LVCS)", ["Centralized (CVCS)", "Distributed (DVCS)", "Remote (RVCS)"], "Types of Version Control Systems"),
    ("In a CVCS, what must an individual do to work on a file?", "Check out the file to lock it, then check it in when done", ["Push it to a peer", "Clone the whole repository", "Merge it with a branch"], "CVCS slide"),
    ("What is one key difference between Git and other version control systems?", "Git stores data as snapshots instead of differences", ["Git stores only the delta between versions", "Git requires a lock before editing", "Git works only on Linux"], "Git slide"),
    ("Which are the three stages of Git?", "Repository, working directory, staging area", ["Committed, modified, staged", "Local, remote, forked", "Add, commit, push"], "Git slide"),
    ("Git and GitHub: which statement is correct?", "GitHub is a repository hosting service that implements Git", ["They are the same thing", "GitHub is a distributed version control system", "Git is a hosting service by Microsoft"], "GitHub slide"),
    ("Which command sets the initial global Git settings?", "git config --global key value", ["git init", "git clone", "git status"], "Setting up Git"),
    ("Which four transport protocols does Git support for accessing a repository?", "Local, SSH, Git, HTTP", ["FTP, SMTP, SSH, HTTP", "Local, Telnet, Git, HTTPS", "SSH, Git, TCP, UDP"], "Git clone slide"),
    ("Which command shows the list of files that differ between the working directory and the parent branch?", "git status", ["git diff", "git log", "git pull"], "Git commands"),
    ("What does the .diff symbol @@ indicate?", "The next block of information is starting", ["A line was added", "A line was removed", "A file was added or removed"], ".diff Files slide"),
    ("What does /dev/null indicate in a .diff file?", "A file has been added or removed", ["A line was added", "The next block is starting", "Context lines"], ".diff Files slide"),
    ("What is a fast-forward merge?", "A merge where Git applies the source commits to the target automatically without conflicts", ["A merge that deletes the source branch", "A merge that requires manual edits", "A merge from a remote to a local repo only"], "Branching Features"),
    ("Which command lists all the local branches?", "git branch --list", ["git checkout -b", "git branch -d", "git merge"], "Get a List of all Branches"),
    ("Which is a reason developers write clean code?", "It is easier to understand and to test with automated methods", ["It runs faster on every machine", "It removes the need for comments", "It avoids needing version control"], "Clean Code slide"),
    ("What is the difference between a method and a function?", "A method is associated with an object; a function is standalone", ["A method is standalone; a function belongs to an object", "There is no difference", "A method returns nothing; a function returns a value"], "Methods vs Functions"),
    ("How is a module packaged?", "As a single file that is expected to work independently", ["As a folder of scripts", "As a class with private variables", "As a database"], "Modules slide"),
    ("What does a return statement do?", "Ends the function and returns control to the caller", ["Starts a loop", "Imports a module", "Prints to the screen"], "Return Statements"),
    ("In Python, how are private variables and methods indicated by convention?", "A single leading underscore", ["Double trailing underscore", "The word private", "An asterisk"], "Classes slide"),
    ("When does the code review process happen?", "After the code changes are complete and tested", ["Before any code is written", "Only after deployment", "During requirements gathering"], "Code Review slide"),
    ("Which type of code review is triggered by automatic emails when a check-in is made?", "Email pass-around", ["Formal code review", "Over-the-shoulder", "Change-based"], "Types of Code Reviews"),
    ("Which type of testing examines usability, performance, security, resiliency, and compliance?", "Non-functional testing", ["Unit testing", "Integration testing", "Functional testing"], "Testing slide"),
    ("What is Test-Driven Development (TDD)?", "Writing the tests before writing the application code", ["Writing tests after deployment", "Testing only on the customer's machine", "Skipping unit tests"], "TDD slide"),
    ("What is the first step of the TDD cycle?", "Create a new test", ["Refactor the code", "Write the application code", "Deploy the code"], "TDD slide"),
    ("Which files does PyTest automatically execute?", "Scripts that start with test_ or end with _test.py", ["Only files named main.py", "Any file with .py", "Files ending with _spec.py"], "Unit Testing slide"),
    ("For unittest, what do you subclass?", "The built-in TestCase class", ["The pytest module", "The Test class", "The Suite class"], "Unit Testing slide"),
    ("Which are the three most popular standard formats for exchanging information with remote APIs?", "XML, JSON, and YAML", ["HTML, CSS, and JS", "CSV, XML, and SQL", "JSON, YAML, and INI"], "Data Formats"),
    ("What is the XML prologue?", "The first line in an XML file", ["The last tag of the document", "A comment", "A namespace"], "XML slide"),
    ("Which statement about JSON is correct?", "JSON does not support any standard way to include comments", ["JSON supports comments like XML", "Whitespace is significant in JSON", "JSON is a superset of YAML"], "JSON slide"),
    ("What is YAML in relation to JSON?", "A superset of JSON designed for easier human readability", ["A subset of JSON", "A binary version of JSON", "The parent of HTML"], "YAML slide"),
    ("How do YAML files conventionally start and end?", "Three dashes to start, three dots to end", ["Curly braces", "An XML prologue", "A hash sign"], "YAML slide"),
    ("What is serializing?", "Turning internal data structures into formatted character strings, roughly the opposite of parsing", ["Breaking a message into components", "Checking the syntax of a file", "Compressing a response"], "Parsing and Serializing"),
    ("In the Module 3 lab, which command lists the installed packages of a Python virtual environment?", "pip3 freeze", ["pip3 list --all-only", "pip3 install", "python3 -m venv"], "Lab: Explore Python Development Tools"),
]

M4_NEW = [
    ("What does an API allow?", "One piece of software to talk to another", ["A user to install an OS", "Hardware to boot faster", "A database to compress data"], "What is an API?"),
    ("Which is a use case of APIs given in the module?", "Automation tasks", ["Hardware manufacturing", "Battery testing", "Manual data entry"], "Why use APIs?"),
    ("Synchronous APIs respond to a request how?", "Directly, providing data immediately", ["With a response with no data", "Only after a webhook", "Only after polling"], "Synchronous APIs"),
    ("What does an asynchronous API return to signify the request was received?", "A response with no data", ["The full data", "An error code", "A webhook URL"], "Asynchronous APIs"),
    ("What is the benefit of an asynchronous API design?", "The application can continue without being blocked while the server processes the request", ["The application must wait for the response", "Data is returned immediately", "No client is needed"], "Asynchronous APIs"),
    ("Which are the three most popular API architectural styles?", "RPC, SOAP, and REST", ["REST, GraphQL, and gRPC", "SOAP, XML, and JSON", "HTTP, FTP, and SMTP"], "API Architectural Styles"),
    ("Which API style is a request-response model that lets an application make a procedure call to another application?", "Remote Procedure Call (RPC)", ["REST", "Webhook", "GraphQL"], "RPC slide"),
    ("Which are the elements of a SOAP message?", "Envelope, Header, Body, and Fault", ["Head, Body, Footer, and Error", "Envelope, Route, Body, and Tail", "Prologue, Header, Body, and Log"], "SOAP slide"),
    ("Which SOAP property means it can be used over any protocol, such as HTTP, SMTP, TCP, UDP, or JMS?", "Neutral", ["Independent", "Extensible", "Stateless"], "SOAP slide"),
    ("Who authored the REST architectural style?", "Roy Thomas Fielding", ["Alistair Cockburn", "Winston Royce", "Erich Gamma"], "REST slide"),
    ("How many constraints did the author establish for REST?", "Six", ["Three", "Four", "Twelve"], "REST slide"),
    ("Which REST constraint says the server cannot contain session states?", "Stateless", ["Cache", "Layered system", "Code-on-demand"], "REST: stateless"),
    ("Which REST constraint states responses must say whether they are cacheable?", "Cache", ["Stateless", "Client-server", "Uniform interface"], "REST: cache"),
    ("Which is one of the four principles of the REST uniform interface?", "Hypermedia as the engine of application state", ["Session state on the server", "Executable code in responses", "Layered proxies"], "REST: uniform interface"),
    ("Which REST constraint is optional because of the security risks of third-party code?", "Code-on-demand", ["Stateless", "Cache", "Client-server"], "REST: code-on-demand"),
    ("What are the four major components of a REST API request?", "URI, HTTP method, header, and body", ["Scheme, host, port, and path", "Status, header, body, and cookie", "URL, token, key, and query"], "REST API Requests"),
    ("Which URI component specifies whether http or https is used?", "Scheme", ["Authority", "Path", "Query"], "URI slide"),
    ("Which URI component provides additional details for scope, filtering, or to clarify a request?", "Query", ["Scheme", "Authority", "Path"], "URI slide"),
    ("Which URI component is the location of the resource on the server?", "Path", ["Scheme", "Authority", "Query"], "URI slide"),
    ("Which HTTP method is suggested for the Create action?", "POST", ["GET", "PUT", "DELETE"], "HTTP method table"),
    ("Which HTTP method is suggested for a partial update of an existing resource?", "PATCH", ["PUT", "POST", "GET"], "HTTP method table"),
    ("Which REST API requests typically include a body?", "POST, PUT, and PATCH", ["GET, DELETE, and HEAD", "GET only", "DELETE only"], "Body slide"),
    ("If data is provided in the body, which header key specifies its type?", "Content-Type", ["Authorization", "Accept-Encoding", "Cache-Control"], "Body slide"),
    ("Which are the three major components of a REST API response?", "HTTP status, header, and body", ["URI, method, and body", "Scheme, host, and path", "Cookie, token, and key"], "REST API Responses"),
    ("What does the 1xx status category mean?", "Informational", ["Success", "Redirection", "Client error"], "HTTP status categories"),
    ("What does the 3xx status category mean?", "Redirection", ["Informational", "Success", "Server error"], "HTTP status categories"),
    ("Which status code means the request was fulfilled and a resource was created?", "201 Created", ["200 OK", "202 Accepted", "204 No Content"], "Common status codes"),
    ("Which status code means the request was understood but rejected by the server?", "403 Forbidden", ["401 Unauthorized", "404 Not Found", "400 Bad Request"], "Common status codes"),
    ("Which status code means the server currently cannot handle the request?", "503 Service Unavailable", ["500 Internal Server Error", "502 Bad Gateway", "404 Not Found"], "Common status codes"),
    ("Which response header is used by the server to send cookies?", "Set-Cookie", ["Cache-Control", "Content-Type", "Authorization"], "Response headers"),
    ("Which response header specifies directives that must be obeyed by all caching mechanisms?", "Cache-Control", ["Set-Cookie", "Content-Type", "Accept-Encoding"], "Response headers"),
    ("Response pagination lets data be broken into chunks. How do most APIs specify the page to return?", "A query parameter", ["A cookie", "The Authorization header", "The request body"], "Response Pagination"),
    ("Which header does a request use to ask for compressed data?", "Accept-Encoding", ["Content-Type", "Cache-Control", "Set-Cookie"], "Compressed response data"),
    ("What does authentication prove?", "The user's identity", ["What the user may access", "How many requests are allowed", "The data format"], "Authentication vs Authorization"),
    ("What does authorization define?", "The user's access to perform the action on a resource", ["The user's identity", "The compression format", "The URI scheme"], "Authentication vs Authorization"),
    ("Which authentication mechanism uses a token generated by an authentication server such as an Identity Service?", "Bearer authentication", ["Basic authentication", "API key", "Cookie"], "Authentication mechanisms"),
    ("What are the two types of API keys?", "Public and private", ["Basic and bearer", "Read and write", "Client and server"], "Authentication mechanisms"),
    ("Which statement about OAuth 2.0 is correct?", "It is not backwards compatible with OAuth 1.0", ["It is backwards compatible with 1.0", "It sends credentials to the third-party app", "It only handles authentication"], "Authorization Mechanisms"),
    ("What is an API rate limit?", "A way for a web service to control how many requests a user or application can make per unit of time", ["The size of a response", "The speed of the network", "The number of servers"], "What are Rate Limits?"),
    ("Which is a purpose of rate limiting?", "Protect against a Denial-of-Service (DoS) attack", ["Increase the response size", "Remove authentication", "Cache responses"], "What are Rate Limits?"),
    ("Which rate limit algorithm processes queued requests at a fixed rate and rejects when the queue is full?", "Leaky bucket", ["Token bucket", "Fixed window counter", "Sliding window counter"], "Leaky bucket"),
    ("Which rate limit algorithm gives each user a defined number of tokens to use in a time increment?", "Token bucket", ["Leaky bucket", "Fixed window counter", "Sliding window counter"], "Token bucket"),
    ("Which rate limit algorithm assigns a counter to a fixed window of time?", "Fixed window counter", ["Leaky bucket", "Token bucket", "Sliding window counter"], "Fixed window counter"),
    ("Which rate limit algorithm counts requests from the beginning of the window to the current time when a new request is made?", "Sliding window counter", ["Fixed window counter", "Token bucket", "Leaky bucket"], "Sliding window counter"),
    ("Which rate limit header gives the number of requests the requester can still make in the current window?", "X-Rate Limit-Remaining", ["X-Rate Limit-Limit", "X-Rate Limit-Reset", "Content-Length"], "Knowing the Rate Limit"),
    ("Which HTTP status codes are most commonly used when the rate limit is exceeded?", "429 Too Many Requests or 403 Forbidden", ["200 OK or 201 Created", "301 or 302", "500 or 503"], "Exceeding the Rate Limit"),
    ("Why are webhooks also called reverse APIs?", "Applications subscribe to the webhook server by registering with the provider", ["They send data backwards", "They only use GET", "They need no server"], "What is a Webhook?"),
    ("Which requirement applies to an application consuming a webhook?", "It must register a URI on the webhook provider", ["It must poll the provider every minute", "It must use only XML", "It must run only once a day"], "Consuming a Webhook"),
    ("Which Python exception in the module indicates a URI missing its scheme?", "MissingSchema", ["ConnectionRefused", "SSLError", "TimeoutError"], "Troubleshooting: invalid URI"),
    ("In Python requests, which parameter turns off certificate verification in a lab?", "verify=False", ["cert=None", "ssl=False", "timeout=0"], "Troubleshooting: invalid certificate"),
    ("Which status code means the client must first authenticate with a proxy?", "407 Proxy Authentication Required", ["401 Unauthorized", "403 Forbidden", "409 Conflict"], "2xx and 4xx status codes"),
    ("Which status code means the request conflicts with the current state of the resource, for example an edit conflict?", "409", ["400", "404", "415"], "2xx and 4xx status codes"),
    ("Which status code is returned when the client sends a body format the server does not support, such as XML to a JSON-only server?", "415 Unsupported Media Type", ["400 Bad Request", "406 Not Acceptable", "500 Internal Server Error"], "2xx and 4xx status codes"),
    ("Which status code means the server, acting as a gateway or proxy, did not receive a timely response from an upstream server?", "504 Gateway Timeout", ["502 Bad Gateway", "503 Service Unavailable", "501 Not Implemented"], "5xx status codes"),
    ("Which status code means the server does not support the functionality required to fulfill the request?", "501 Not Implemented", ["500 Internal Server Error", "502 Bad Gateway", "504 Gateway Timeout"], "5xx status codes"),
    ("What are the three steps to troubleshoot errors listed in the module?", "Check the return code, check the response body, use a status code reference", ["Restart the server, reinstall Python, clear the cache", "Change the method, change the URI, change the header", "Add tokens, add keys, add cookies"], "Interpreting Status Codes"),
    ("Can server-side issues be resolved from the API client side?", "No, contact the administrator of the API server", ["Yes, by changing the URI", "Yes, by turning off verify", "Yes, by changing the method"], "No response from API server"),
    ("Which codes are client-side errors and which are server-side errors?", "4xx client-side, 5xx server-side", ["2xx client-side, 5xx server-side", "4xx server-side, 5xx client-side", "1xx client-side, 3xx server-side"], "Summary"),
]
