"""Hand-written, slide-literal ML cards (Module 1 and Module 2). Choice questions only.
Card = (question, correct, [three wrong], why)."""

DECK = [
    # ---- Module 1
    ("Who defined machine learning as the ability to learn without being explicitly programmed?", "Arthur Samuel, 1959",
     ["Alan Turing, 1950", "Tom Mitchell, 1997", "Andrew Ng, 2011"], "M1: What is Machine Learning"),
    ("Machine learning sits at the intersection of which fields?", "Statistics, artificial intelligence, and computer science",
     ["Physics, chemistry, and biology", "Networking, security, and databases", "Economics, law, and statistics"], "M1: What is Machine Learning"),
    ("Which is another name for machine learning given in the slides?", "Predictive analytics",
     ["Rule-based programming", "Data warehousing", "Network analytics"], "M1: What is Machine Learning"),
    ("In the E, T, P definition, performance at task T improves with what?", "Experience E",
     ["Performance measure P", "A larger task T", "A faster computer"], "M1: Formal definition"),
    ("A rule-based algorithm runs on conditions. What does a machine learning algorithm run on?", "Data (or experience)",
     ["Conditions", "Hand-written rules", "Compiler flags"], "M1: ML vs rule-based"),
    ("Which are the three types of machine learning in the slides?", "Supervised, unsupervised, and reinforcement",
     ["Supervised, regression, and clustering", "Classification, regression, and boosting", "Deep, shallow, and linear"], "M1: Types of ML"),
    ("In the ML workflow, what is Phase 2?", "Prediction: new data goes into the trained model",
     ["Learning: training data is preprocessed", "Testing: performance is measured", "Preprocessing: data is cleaned and formatted"], "M1: How does ML work"),
    ("Which Python library is the most prominent tool for ML?", "Scikit-learn", ["Matplotlib", "SciPy", "Jupyter"], "M1: Why Python"),
    ("Which Python library is for data wrangling and analysis?", "Pandas", ["Matplotlib", "NumPy", "Anaconda"], "M1: Why Python"),
    ("Anaconda is described in the slides as what?", "A Python distribution for large-scale data processing and scientific computing",
     ["A plotting library", "A library for data wrangling", "An interactive environment in the browser"], "M1: Why Python"),
    ("Which three data quality problems do the slides list for real data?", "Incompleteness, noise, and inconsistency",
     ["Size, speed, and cost", "Bias, variance, and noise", "Duplicates, outliers, and scaling"], "M1: Data Preprocessing"),
    ("Which is a feature engineering technique, not data cleansing?", "Feature encoding",
     ["Removing duplicates", "Sorting out missing data", "Reducing noisy data"], "M1: Preprocessing techniques"),
    ("Which EDA activity identifies unusual data points?", "Outlier detection",
     ["Correlation analysis", "Hypothesis testing", "Summary statistics"], "M1: EDA"),
    ("The number of students in a class is what kind of data?", "Discrete", ["Continuous", "Categorical only", "Unbounded"], "Formative Q1"),
    ("Which data ethics principle says an individual owns their personal information?", "Ownership",
     ["Transparency", "Intention", "Outcomes"], "M1: Data Ethics"),
    # ---- Module 2
    ("What does labeled training data in supervised learning contain?", "The input data and the corresponding correct output",
     ["Only the input data", "Only the correct output", "Input data with no labels"], "M2: Supervised Learning"),
    ("Which task has a categorical target variable?", "Classification", ["Regression", "Clustering", "Forecasting"], "M2: Classification"),
    ("Which algorithm do the slides list under classification?", "Logistic Regression",
     ["Lasso Regression", "Simple Linear Regression", "Multivariate Regression"], "M2: Classification algorithms"),
    ("A model that predicts accurately on new, unseen data is said to be able to do what?", "Generalize",
     ["Overfit", "Underfit", "Memorize"], "M2: Generalization"),
    ("A model works very well on the training set but poorly on new data. What is this?", "Overfitting",
     ["Underfitting", "Generalization", "Regularization"], "M2: Overfitting"),
    ("A model does badly even on the training set because it is too simple. What is this?", "Underfitting",
     ["Overfitting", "Generalization", "Boosting"], "M2: Underfitting"),
    ("Which does NOT help a model avoid overfitting, according to the slides?", "Duplicating the same data points",
     ["Collecting more varied data points", "Collecting a larger variety of data", "Choosing a simpler model"], "M2: Model complexity and dataset size"),
    ("In the slides, what is variance?", "Error from sensitivity to noise and fluctuations in the training data",
     ["Error from wrong or too-simple assumptions", "The average of the target values", "The spread of the test labels"], "M2: What is a Good Model"),
    ("What does building a k-NN model consist of?", "Only storing the training dataset",
     ["Fitting a straight line", "Learning a tree of if/else questions", "Minimizing the mean squared error"], "M2: k-Nearest Neighbors"),
    ("For k-NN classification with more than one neighbor, how is the label assigned?", "By voting: the majority class among the neighbors",
     ["By averaging the neighbors' labels", "By taking the farthest neighbor", "By using the first neighbor only"], "M2: k-NN"),
    ("For k-NN regression with more than one neighbor, what is the prediction?", "The average (mean) of the neighbors' targets",
     ["The majority class", "The nearest neighbor's target only", "The largest neighbor target"], "M2: k-NN regression"),
    ("Using k = 1 in k-NN makes the model what?", "More complex, with a jagged boundary",
     ["Less complex, with a smooth boundary", "Unable to predict", "Equal to linear regression"], "Formative Q9"),
    ("Which distance measure does k-NN use by default?", "Euclidean", ["Manhattan", "Cosine", "Hamming"], "M2: k-NN parameters"),
    ("What does the score method return for a regressor?", "The R2 score", ["The accuracy", "The mean squared error", "The number of neighbors"], "M2: Estimation of regression"),
    ("An R2 of 0 corresponds to what?", "A constant model that predicts the mean of the training targets",
     ["A perfect prediction", "A model worse than the mean", "A model that fits only the test set"], "M2: Estimation of regression"),
    ("What does a negative R2 mean?", "The model predicts worse than the average",
     ["The model is perfect", "The data has no outliers", "The model is underfitting only"], "Formative Q11"),
    ("In y-hat = w*x + b, what is b also called?", "The intercept (also the offset or bias)", ["The weight", "The coefficient", "The slope"], "Formative Q12"),
    ("What does ordinary least squares (linear regression) minimize on the training set?", "The mean squared error",
     ["The number of features", "The alpha penalty", "The accuracy"], "M2: Linear Regression"),
    ("Linear regression on the wave dataset scored about 0.66 on both train and test. What does that suggest?", "Underfitting",
     ["Overfitting", "Perfect generalization", "Data leakage"], "M2: Linear Regression"),
    ("Which regularization does Ridge regression use?", "L2", ["L1", "L0", "No regularization"], "M2: Ridge Regression"),
    ("In Ridge regression, what does a larger alpha do?", "Raises the penalty and pushes the weights toward zero",
     ["Lowers the penalty", "Removes the penalty", "Turns weights exactly to zero"], "Formative Q13"),
    ("Which model can make some coefficients exactly zero?", "Lasso (L1)", ["Ridge (L2)", "Ordinary least squares", "k-NN"], "M2: Lasso"),
    ("In LogisticRegression, what does a higher value of C mean?", "Less regularization",
     ["More regularization", "A smaller number of neighbors", "A larger alpha"], "M2: LogisticRegression vs LinearSVC"),
    ("Which Naive Bayes classifier is for integer count data?", "MultinomialNB", ["GaussianNB", "BernoulliNB", "LinearNB"], "Formative Q16"),
    ("A decision tree learns what?", "A hierarchy of if/else questions", ["A best-fit line", "A voting rule over neighbors", "A kernel function"], "M2: Decision Trees"),
    ("What is a random forest's way of reducing overfitting?", "Averaging many randomized trees built on bootstrap samples",
     ["Using one very deep tree", "Fixing the error of the previous tree", "Scaling the features to 0-1"], "M2: Random Forests"),
    ("How does gradient boosting build its trees?", "Each new tree compensates for the error of the previous tree",
     ["All trees are built independently", "Each tree is built from the whole dataset with no changes", "Trees are averaged with no ordering"], "M2: Gradient Boosting"),
    ("Which preprocessing method do the slides use to scale features for a kernel SVM?", "MinMaxScaler (scale to between 0 and 1)",
     ["One-hot encoding", "Removing duplicates", "Discretization"], "M2: Preprocessing Data for SVMs"),
]

MOCK = [
    # ---- Module 1
    ("A company wants a program that improves at spotting spam as it sees more emails. Which E, T, P part is the spam spotting?", "The task T",
     ["The experience E", "The performance measure P", "The training time"], "M1: Formal definition"),
    ("Which statement contrasts rule-based programming and machine learning correctly?", "Rule-based uses conditions; machine learning uses data",
     ["Rule-based uses data; machine learning uses conditions", "Both use only conditions", "Both use only labels"], "M1: ML vs rule-based"),
    ("Why can machines suit routine, repetitive tasks better than people, per the slides?", "They work 24/7 and are not affected by fatigue or inattention",
     ["They never need any data", "They always cost more than humans", "They need no maintenance at all"], "M1: Why Machine Learning"),
    ("In the learning phase of the ML workflow, which step comes right after the training data?", "Preprocessing (clean and format the data)",
     ["Prediction", "Deployment", "Monitoring"], "M1: How does ML work"),
    ("A dataset has blank cells, wrong records, and conflicting records. Which problems is it showing?", "Incompleteness, noise, and inconsistency",
     ["Variance and bias", "Overfitting and underfitting", "Duplication only"], "M1: Data Preprocessing"),
    ("Which library is the primary scientific plotting library?", "Matplotlib", ["Pandas", "NumPy", "Scikit-learn"], "M1: Why Python"),
    ("A boxplot is used to spot points far from the rest of the data. Which EDA activity is this?", "Outlier detection",
     ["Hypothesis testing", "Feature scaling", "Data reduction"], "M1: EDA"),
    ("After a model is deployed, its performance slowly worsens as real-world data changes. Which stage should catch this?", "Monitoring",
     ["Training", "Validation", "Preprocessing"], "M1: Model Deployment"),
    ("A study causes unintended harm to a group even though the intentions were good. Which ethics principle is this about?", "Outcomes (disparate impact)",
     ["Ownership", "Privacy", "Intention"], "M1: Data Ethics"),
    ("Which is personally identifiable information (PII) in the slides?", "Bank account number",
     ["The average of a column", "The name of a library", "The size of a dataset"], "M1: Data Ethics"),
    # ---- Module 2
    ("Predicting a house price is which kind of supervised task?", "Regression (the target is continuous)",
     ["Classification, because prices are labels", "Clustering", "Reinforcement learning"], "M2: Supervised Learning"),
    ("Filtering e-mails into spam or not spam is which kind of task?", "Binary classification",
     ["Multiple classification", "Regression", "Clustering"], "M2: Classification"),
    ("A model scores 99 percent on training data and 62 percent on test data. What is the likely problem?", "Overfitting",
     ["Underfitting", "Good generalization", "A scaling error only"], "M2: Overfitting"),
    ("A model scores 55 percent on both training and test data. What is the likely problem?", "Underfitting",
     ["Overfitting", "Good generalization", "Too much data"], "M2: Underfitting"),
    ("As model complexity keeps increasing, what happens to the training score and to generalization?", "Training keeps improving, but generalization eventually drops",
     ["Both always improve", "Training drops, generalization improves", "Neither changes"], "M2: Model Complexity Curve"),
    ("Which describes the best model on the complexity curve?", "The sweet spot between underfitting and overfitting",
     ["The most complex model", "The simplest model", "The model with 100 percent training accuracy"], "M2: Model Complexity Curve"),
    ("A rule is 100 percent accurate on only 12 rows. Why shouldn't you trust it yet?", "Many other rules would fit 12 rows equally well",
     ["Twelve rows is the ideal size", "Accuracy cannot be measured on training data", "Rules never work on small data"], "M2: The boat example"),
    ("Which is the slide definition of bias?", "Error from wrong or too-simple assumptions in the learning algorithm",
     ["Error from sensitivity to noise", "The difference between train and test sets", "The size of the training set"], "M2: What is a Good Model"),
    ("In k-NN, increasing k from 1 to a large value moves the model toward what?", "Underfitting",
     ["Overfitting", "Perfect memorization", "A decision tree"], "M2: Model complexity of k-NN"),
    ("On the plot of k-NN accuracy against n_neighbors, where is the best performance?", "Somewhere in the middle",
     ["At n_neighbors = 1", "At the largest n_neighbors", "It is the same everywhere"], "M2: Model Complexity of K-NN"),
    ("Which is a strength of k-NN listed in the slides?", "Easy to understand and works well without special adjustments",
     ["Fast with very many samples", "Great on sparse datasets", "Needs no distance measure"], "M2: k-NN strengths"),
    ("Which is a weakness of k-NN listed in the slides?", "Does not work well with sparse datasets",
     ["Hard to understand", "Needs heavy tuning to work at all", "Cannot do regression"], "M2: k-NN weaknesses"),
    ("A model's R2 is -0.4. How does it compare with always predicting the mean?", "It is worse",
     ["It is better", "It is exactly the same", "R2 cannot compare to the mean"], "M2: Estimation of regression"),
    ("Where does scikit-learn store a linear model's weights and intercept?", "coef_ and intercept_",
     ["weights_ and bias_", "slope_ and offset_", "w_ and b_"], "M2: Linear Regression"),
    ("A linear regression on 105 features shows a huge gap between train and test R2. What should you try?", "Ridge regression to control complexity",
     ["Remove all regularization", "Use fewer training rows", "Lower k in k-NN"], "M2: Ridge Regression"),
    ("Which statement about Ridge vs Lasso is correct?", "Lasso can zero out features, while Ridge only shrinks them toward zero",
     ["Ridge can zero out features, Lasso cannot", "Both set every weight to exactly zero", "Neither uses a penalty"], "M2: Ridge vs Lasso"),
    ("Only a few of many features matter and you want an easy-to-read model. Which is the better pick per the slides?", "Lasso",
     ["Ridge", "Ordinary least squares", "k-NN"], "M2: Ridge vs Lasso"),
    ("Lasso with alpha 1.0 used only 4 of 105 features and scored badly. What fixes this?", "Lowering alpha",
     ["Raising alpha", "Adding more duplicates", "Removing the test set"], "M2: Lasso"),
    ("Which is true of LogisticRegression?", "It is a classification algorithm despite its name",
     ["It is a regression algorithm", "It cannot output probabilities", "It is a clustering method"], "M2: LogisticRegression vs LinearSVC"),
    ("Which Naive Bayes classifier suits continuous data?", "GaussianNB", ["MultinomialNB", "BernoulliNB", "CountNB"], "M2: Naive Bayes"),
    ("Why are Naive Bayes models efficient?", "They look at each feature individually and collect simple per-class statistics",
     ["They search all feature interactions", "They build hundreds of trees", "They store the full dataset"], "Formative Q15"),
    ("A decision tree regressor is asked to predict outside the range of its training data. What happens?", "It cannot extrapolate beyond the training range",
     ["It extrapolates perfectly", "It switches to a linear model", "It always predicts zero"], "M2: Decision Tree Regression"),
    ("Which is a tree-based method that builds many independent trees on bootstrap samples?", "Random forest",
     ["Gradient boosting", "Kernel SVM", "Ridge regression"], "M2: Random Forests"),
    ("Gradient boosting hits 100 percent training accuracy. What are two ways the slides give to reduce overfitting?", "Limit the maximum depth or lower the learning rate",
     ["Raise the learning rate or add depth", "Remove the test set or add noise", "Use more trees and no limit"], "M2: Gradient Boosting Classifier"),
    ("In an RBF-kernel SVM, a small gamma means what?", "A large kernel radius, so many points count as close",
     ["A tiny radius", "No regularization", "A linear kernel"], "M2: Tuning SVM Parameters"),
    ("Why must features be rescaled before an RBF SVM on the Breast Cancer data?", "The features have very different ranges and SVMs are sensitive to scale",
     ["SVMs only accept integer data", "Scaling removes the support vectors", "Scaling is required for k-NN only"], "M2: Preprocessing Data for SVMs"),
]

# Trimmed to the agreed sizes (40 cards, 30 mock items); the dropped ones were the lowest-yield or duplicated another item.
_DROP_DECK = ("Which is another name for machine learning", "Which algorithm do the slides list under classification",
              "Which distance measure does k-NN use")
_DROP_MOCK = ("Which is personally identifiable", "Which library is the primary scientific plotting",
              "A model's R2 is -0.4", "Where does scikit-learn store", "Which Naive Bayes classifier suits continuous",
              "Which is a weakness of k-NN")
DECK = [c for c in DECK if not c[0].startswith(_DROP_DECK)]
MOCK = [c for c in MOCK if not c[0].startswith(_DROP_MOCK)]
assert len(DECK) == 40, len(DECK)
assert len(MOCK) == 30, len(MOCK)
