"""Cards from the picture slides (Module 1 and Module 2). Choice questions only. Card = (question, correct, [three wrong], why)."""

PICTURE = [
    ("How many types of machine learning does the Types of Machine Learning picture show?", "Four",
     ["Two", "Three", "Five"], "M1: Types of Machine Learning"),
    ("Which type appears in the picture besides supervised, unsupervised, and reinforcement learning?", "Semi-supervised learning",
     ["Transfer learning", "Federated learning", "Self-learning"], "M1: Types of Machine Learning"),
    ("In the four-stage ML workflow picture, which stage includes splitting the data?", "Data preparation",
     ["Project setup", "Modeling", "Deployment"], "M1: ML Workflow"),
    ("In the four-stage ML workflow picture, which stage includes hyperparameter tuning?", "Modeling",
     ["Data preparation", "Project setup", "Deployment"], "M1: ML Workflow"),
    ("Which language ranks number 1 for machine learning in the slides?", "Python", ["R", "Java", "C++"], "M1: Top Programming Languages for ML"),
    ("Which Python library from the slides is used for web crawling?", "Scrapy", ["Seaborn", "SQLModel", "Keras"], "M1: Top 10 Python Libraries"),
    ("Which Python library from the slides is for deep learning?", "Keras", ["Pandas", "Matplotlib", "SciPy"], "M1: Top 10 Python Libraries"),
    ("In the rule-based algorithm flowchart, what decides which code runs?", "A condition that is true or false",
     ["The training data", "A learned model", "The accuracy score"], "M1: Rule-based vs ML"),
    ("In the machine learning diagram, what happens to new data?", "It goes into the model, which gives a prediction",
     ["It becomes training data first", "It is converted into rules by hand", "It is discarded"], "M1: Rule-based vs ML"),
    ("On the scenario chart, which approach fits complex rules at a large scale?", "Machine learning algorithms",
     ["Manual rules", "Rule-based algorithms", "Simple problems"], "M1: Application Scenarios"),
    ("On the scenario chart, which approach fits simple rules at a large scale?", "Rule-based algorithms",
     ["Machine learning algorithms", "Manual rules", "Neural networks"], "M1: Application Scenarios"),
    ("How do the slide diagrams relate machine learning and artificial intelligence?", "Machine learning is a subset of AI",
     ["AI is a subset of machine learning", "They are unrelated", "Machine learning replaces data science"], "M1: What is Machine Learning"),
    ("What do data scientists spend most of their time on, according to the pie chart?", "Data cleaning and organization (60 percent)",
     ["Data mining", "Improving algorithms", "Creating training sets"], "M1: Data Preprocessing"),
    ("Which is the first of the six key steps in data preprocessing?", "Data profiling",
     ["Data cleansing", "Data reduction", "Data validation"], "M1: Key Steps in Data Preprocessing"),
    ("In the messy table, the same Id appearing on two rows is marked as what?", "An invalid duplicate item",
     ["A missing value", "A misspelling", "An attribute dependency"], "M1: Data Preprocessing"),
    ("What does the slide say about a single outlier in a regression?", "It can throw off the regression estimate",
     ["It never changes the regression line", "It always improves the fit", "It is removed automatically"], "M1: Data Preprocessing"),
    ("Which kind of plots does the EDA slide say visualize the count of values?", "Bar plots and histograms",
     ["Scatter plots and boxplots", "Heatmaps only", "Line charts"], "M1: EDA"),
    ("In the Titanic example, which imputation is used for a categorical column such as Embarked?", "Most-frequent imputation",
     ["Mean imputation", "Median imputation", "Deleting the column"], "M1: EDA"),
    ("In the column transformation slide, which is used for numerical data like Age and Fare?", "Standard scaling",
     ["Ordinal encoding", "Feature selection", "Mean imputation"], "M1: EDA"),
    ("Which data subject right appears in the slides?", "Right to data portability",
     ["Right to free storage", "Right to sell data", "Right to anonymous AI"], "M1: Data Subject Rights"),
    ("On the model complexity curve, what does training accuracy do as complexity increases?", "It keeps rising",
     ["It keeps falling", "It peaks then falls", "It stays flat"], "M2: Model Complexity Curve"),
    ("On the model complexity curve, what does test (generalization) accuracy do as complexity increases?", "It rises, peaks at the sweet spot, then falls",
     ["It keeps rising", "It keeps falling", "It stays flat"], "M2: Model Complexity Curve"),
    ("In the bias and variance dartboard picture, which combination is the good model?", "Low bias and low variance",
     ["High bias and low variance", "Low bias and high variance", "High bias and high variance"], "M2: What is a Good Model"),
    ("As n_neighbors increases in the k-NN plot, what happens to training accuracy?", "It falls",
     ["It rises", "It stays at 1.0", "It stays flat"], "M2: Model Complexity of K-NN"),
    ("In the supervised learning picture, what are weather, temperature, and wind speed?", "The input x (features)",
     ["The output y", "The label", "The goal"], "M2: Supervised Learning"),
    ("What is the Ridge regression cost function?", "MSE plus alpha times the sum of the squared weights",
     ["MSE plus alpha times the sum of the absolute weights", "MSE alone", "Alpha times the number of features"], "M2: Ridge Regression"),
    ("What is the Lasso cost function penalty?", "Alpha times the sum of the absolute weights (L1)",
     ["Alpha times the sum of the squared weights", "Alpha times the largest weight", "No penalty"], "M2: Lasso"),
    ("In the animal decision tree picture, what are Hawk, Penguin, Dolphin, and Bear?", "Terminal nodes",
     ["The root node", "Edges", "Tests"], "M2: Decision Trees"),
    ("In the RAM price example, what does the decision tree prediction do after the training range?", "It stays flat because trees cannot extrapolate",
     ["It keeps following the trend", "It drops to zero", "It matches the linear model"], "M2: Decision Tree Regression"),
    ("Which statement about regression is safest for the exam?", "Regression predicts continuous real numbers",
     ["Regression predicts class labels", "Regression predicts only whole numbers", "Regression needs a categorical target"], "Q17 and M2: Regression"),
]
assert len(PICTURE) == 30, len(PICTURE)
